apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hash-md5
  name: hash-md5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-md5
  strategy: {}
  template:
    metadata:
      labels:
        app: hash-md5
    spec:
      containers:
      - image: dleurs/hash-md5:1.0.0
        name: hash-md5
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
# Test with kubectl run --namespace default testing-nodejs-app-2 --rm --tty -i --restart='Never' --image curlimages/curl --command -- curl -v http://hash-md5.default.svc.cluster.local/Dimitri
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hash-md5
  name: hash-md5
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hash-md5
  type: ClusterIP
status:
  loadBalancer: {}